name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: oldrooster/simple-budget:latest

    - name: Read README.md
      id: readme
      run: |
          # Save the content of README.md to an environment variable
          README_CONTENT=$(cat README.md)
          echo "README_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$README_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

    - name: Update Docker Hub Repo Overview
      run: |
          README_CONTENT=$(cat README.md | jq -Rs .) # Read and escape README.md content
          curl -X PATCH \
          -H "Authorization: Bearer ${{ secrets.DOCKER_HUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "{\"full_description\": $README_CONTENT}" \
          https://hub.docker.com/v2/repositories/oldrooster/simple-budget/
        